apiVersion: v1
kind: Pod
metadata:
  name: temperature-service-pod
  labels:
    component: web
spec:
  containers:
    - name: temperature-service
      image: newarcher/temperature-service
      ports:
        - containerPort: 30000