apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: temperature-service
  template:
    metadata:
      labels:
        component: temperature-service
    spec:
      containers:
        - name: temperature-service
          image: newarcher/temperature-service
          ports:
            - containerPort: 8091
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABAE
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD

