apiVersion: v1
kind: Service
metadata:
  name: meteo-station-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: meteo-station-service
  ports:
    - port: 8090
      targetPort: 8090